### ISSUE TITLE
The Invoice payment type should be disabled when selling downloadable / virtual products

### ISSUE THREAD

**Issue by bve-9384** [PayEx/payex-magento2-pops#58]
We want to sell downloadable products in Sweden, in which case the customer should not be able to select the PayEx invoice payment type (see the PayEx terms & conditions).

The PayEx plugin allows Invoice payments for orders without a delivery address, which we think is wrong. 

It seems that a solution could be to catch the "payment_method_is_active" event, check if the order has a shipment address and then disable to payment type. 

Found examples here:
https://magento.stackexchange.com/questions/154155/magento-2-disable-cash-on-delivery-for-downloadable-products
https://magento.stackexchange.com/questions/143022/magento-2-payment-method-for-certain-customer-groups/143026

Any recommendation?

**Comment by olegisk** [comment]
Hello, @bve-9384 
You need to develop extension for magento that will check cart.
Something like that https://magento.stackexchange.com/questions/186150/magento2-how-to-get-all-payment-methods-in-plugin
