### ISSUE TITLE
No Complete for currency EURO

### ISSUE THREAD

**Issue by patrickhrml** [PayEx/payex-magento2-pops#66]
A merchant is having issues with EURO through Magento2, when the currency changes from SEK to EUR it doesn't send Complete for the transaction. Transaction Callback is sent and OK'd but Complete is never sent.

Directly changing back to SEK, the flow works as it should. I don't have Magento2 available to test this myself.

**Comment by aait** [comment]
Hi @patrickhrml 
Is it possible to get access to the shop to investigate this specific problem? Please contact us per email

**Comment by saumoor** [comment]
Status on this issue?

**Comment by aait** [comment]
@saumoor we need access to the shop

**Comment by saumoor** [comment]
Access was sent to you on mail 
Any update? @aait
