### ISSUE TITLE
Wrong success callback

### ISSUE THREAD

**Issue by tereshvti** [PayEx/payex-magento2-pops#76]
We received success URL hit for an order. Payment is not authorized for it. Can you explain why it happened? In module's code success callback should be 'payex/psp/success', but 'checkout/onepage/success' was accessed.

46.9.119.209 - - [2019-05-29T10:53:04+00:00] "GET /checkout/onepage/success/ HTTP/1.1" 200 32411 "https://ecom.payex.com/vipps/payments/authorize/61af23251d3a3ceaa779202befe3492a39a15dd20580207cfa5cf422386bce43" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15"

**Comment by aait** [comment]
Hi,

Correct callkab url is payex/psp/callback

**Comment by tereshvti** [comment]
> Hi,
> 
> Correct callback url is payex/psp/callback. Make sure you have the right callback url entered in the PayEx Merchant Admin panel.

Hmm.. I thought this callback is only taken from payment initialization data. Pushed from Magento

**Comment by aait** [comment]
Hi,

Are you using the REST API or the old PIM/POPS api? If you post the url to your admin page I will see.

**Comment by tereshvti** [comment]
Hi, 

I'm not sure what kind of API we are using, but it is PSP VIPPS payment method. Here is the line where successUrl is passed. 
https://github.com/PayEx/payex-magento2-pops/blob/develop/Model/Psp/Vipps.php#L114
But unfortunately user was redirected to default Magento path **checkout/onepage/success**

**Comment by aait** [comment]
Hi, first please check with your PayEx sales representative which API you are using or post the admin url here and I can tell you. After that we can continue with troubleshooting. Thanks.

**Comment by tereshvti** [comment]
Admin URL https://admin.payex.com/psp/dashboard/
https://prnt.sc/o0b21t
Seems like default placeholders. Any other info is needed?

**Comment by aait** [comment]
Hi,
You are using the new REST API. Please repeat your question here https://github.com/PayEx/payex-magento2-checkout/issues

**Comment by asbjornu** [comment]
This repository and module implemented support for the REST API a few years ago, so this issue is submitted in the correct repository. We are still not sure how to best fix the problem, though. Reopening.

**Comment by tereshvti** [comment]
> This repository and module implemented support for the REST API a few years ago, so this issue is submitted in the correct repository. We are still not sure how to best fix the problem, though. Reopening.

Hello :)
I think correct callback was pushed on initialize and there are no options it can be wrong. The reason is why Payex side redirect after payment authorization was to wrong success URL. Can you check initialize parameters for this payment?
