### ISSUE TITLE
PHP 7.3 not supported

### ISSUE THREAD

**Issue by vovarudakov94** [PayEx/payex-magento2-pops#79]
Currently, your module not officially supports PHP 7.3
`"php": "~7.0.0|~7.1.0|~7.2.0",`
We have PHP 7.3.11 in our Magento cloud.
Please add support for PHP 7.3.

**Comment by bve-9384** [comment]
I read that this solution will be discontinued on June 30th 2020 (see http://www.payexpim.com/).

**Comment by vovarudakov94** [comment]
thank you, as I understood we should switch to this solution?
https://marketplace.magento.com/creationlabs-module-swedbank.html

**Comment by bve-9384** [comment]
They sent me this link, it seems that a Magento plugin is not yet available
https://www.swedbankpay.com/moveto

Den tors 5 mars 2020 11:17Vova Rudakov <notifications@github.com> skrev:
